### ISSUE TITLE
センサー情報受け取り時のエラー処理

### ISSUE THREAD

**Issue by TbrtTkyk** [u8-zawa/HoloLens2Iot#85]
実行時、SensorDataManagerに対して

{name =, datas = [], times = [],
stat = {latest = 0, avg = 0, max = 0, min=0}}

のデータを入れようとして、UpdateData()内でDictionaryのキーにnullを指定したためArgumentNullExceptionが発生。
原因は{"error": "Node is offline"}というメッセージを受信した際にJsonに無理矢理変換して処理を行うためだと考えている。

不正なJSONメッセージの受信に対するエラー処理を追加する。

**Comment by u8-zawa** [comment]
> 原因は{"error": "Node is offline"}というメッセージを受信した際にJsonに無理矢理変換して処理を行うためだと考えている。

**SensorDataの形式じゃない場合、jsonデシリアライズは行われないと思われる。**

**Comment by u8-zawa** [comment]
jsonデシリアライズをするかしないかの部分
```
// payloadが設定されていて、中身がJsonの場合
if (payload != "" && IsJson(payload))
{
  sensorData = SensorData.FromJson(payload);
  Debug.Log(sensorData.ToString());

  MemorySensorData(sensorData);
}
```
（C:\UNPR\HoloLens2Iot\Assets\Scripts\MqttController.cs, 117～124行目、141～148行目）

**Comment by u8-zawa** [comment]
SensorDataの形式かどうか判別する部分
```
private Boolean IsJson(string data)
{
  try
  {
    JsonUtility.FromJson<SensorData>(data);
  } catch 
  {
    return false;
  }
  return true;
}
```
（C:\UNPR\HoloLens2Iot\Assets\Scripts\MqttController.cs, 168～178行目）

**Comment by u8-zawa** [comment]
この仕組みがそもそも良くない可能性あり。
